name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          files: ci/docker-bake.hcl
          targets: test
          push: false
          load: true
      -
        name: Run
        run: docker run --network host -v /var/run/docker.sock:/var/run/docker.sock --rm test
    
